version: "3"
services: 
  client:
    build: /client
    ports:
      - "3000:3000"
  server:
    build: /server
    ports:
      - "5000:5000"
    environment: 
      - CONNECTION_URL = mongodb+srv://admin:vyuQt8jj3qzaOUk@cluster0.8fhqr.mongodb.net/<dbname>?retryWrites=true&w=majority
      - PORT = 5000
      - TOKEN_SECRET = sY1hgypILYUw870JWd4wV7TAIMU2K2V2YYKd9N266LpfFt4TmXEafOtlAOQZWlrMCH/H7idpEDyAtpfN
      - AZURE_OCR_KEY = d057adf11c3c4c658b6a8882a64ad6e7
      - AZURE_OCR_ORIGIN = eastus